#################################################
# APPLICATION
#################################################

spring.application.name=customer-service
server.port=8081

#################################################
# LOGGING
#################################################

logging.file.name=logs/customer-service.log

logging.level.root=INFO
logging.level.com.alisha.customerservice=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n

#################################################
# ROLLING POLICY
#################################################

logging.logback.rollingpolicy.max-file-size=10MB

logging.logback.rollingpolicy.max-history=30

logging.logback.rollingpolicy.total-size-cap=1GB

logging.logback.rollingpolicy.file-name-pattern=logs/customer-service-%d{yyyy-MM-dd}.%i.log

#################################################
# PostgresSql
#################################################
db.host=host.docker.internal

spring.datasource.url=jdbc:postgresql://${db.host}:5432/customerdb

spring.datasource.username=postgres

spring.datasource.password=Sql@1234

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#################################################
# JWT
#################################################

jwt.private-key=classpath:keys/private.pem
jwt.public-key=classpath:keys/public.pem
jwt.expiration=3600000

#################################################
# Actuator
#################################################

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
